apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod-one
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: data-writer
      image: busybox
      command:
        - /bin/sh
        - -c
        - |
          echo "Writing data to /data/output.txt..."
          echo "Random value: $RANDOM" > /data/output.txt
          echo "Sleeping for 5 seconds..."
          sleep 5
          
          if [ $((RANDOM % 2)) -eq 0 ]; then
           echo "Exiting with success"
           exit 0
          else
           echo "Exiting with failure"
           exit 1
          fi
      volumeMounts:
        - mountPath: /data
          name: storage
  volumes:
    - name: storage
      emptyDir: {}
