apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    control-plane: controller-manager
    app.kubernetes.io/part-of: ephemeralvolumeautocleanup
  name: controller-manager
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    control-plane: controller-manager
    app.kubernetes.io/part-of: ephemeralvolumeautocleanup
  name: controller-manager-cluster-role
rules:
  - apiGroups: ["cleanup.makro.com"]
    resources: ["ephemeralvolumepolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["cleanup.makro.com"]
    resources: ["ephemeralvolumepolicies/finalizers"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["cleanup.makro.com"]
    resources: ["ephemeralvolumepolicies/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "list", "update", "delete", "patch", "get", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "update", "delete", "patch", "get", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    control-plane: controller-manager
    app.kubernetes.io/part-of: ephemeralvolumeautocleanup
  name: controller-manager-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controller-manager-cluster-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system