---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cleanup.makro.com
  resources:
  - ephemeralvolumepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cleanup.makro.com
  resources:
  - ephemeralvolumepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - cleanup.makro.com
  resources:
  - ephemeralvolumepolicies/status
  verbs:
  - get
  - patch
  - update
